modLoader="javafml"
loaderVersion="[32,)"
license="All rights reserved"
issueTrackerURL="https://github.com/teamauroramods/EnhancedMushrooms/issues"

[[mods]]
    modId="enhanced_mushrooms"
    version="${file.jarVersion}"
    displayName="Enhanced Mushrooms"
    displayURL="https://discord.gg/BgE4EpP"
    logoFile="logo.png"
    authors="Team Aurora"
    description="New mushroom-based wood types and a couple mushroom foods."

[[dependencies.enhanced_mushrooms]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.88,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.enhanced_mushrooms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.enhanced_mushrooms]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[2.0.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.enhanced_mushrooms]]
    modId="quark"
    mandatory=false
    versionRange="[r2.2-257,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.enhanced_mushrooms]]
    modId="environmental"
    mandatory=false
    versionRange="[0.1.0,)"
    ordering="AFTER"
    side="BOTH"